env:
  global:
    - secure: "TmNNY4XUITwiuFOgb+Tnh6JuF7u7kuQ8h0CPL82NeHf/kqF72Vka75jMFDu5Q+hWKQNasOBwfJb4KVG0dFSqokcbXbAUluGmpls4PulLn8wMMSd3RNb+UD+26R2f/sTeuA5TTbu8X2+v8KShQVESsscGH002lF5DKkk1KnZDnaXl+uJdETbww2KXoHg3zzIMjIHQExqMBVucsdI/Ml2gKws5ko+/tSG1KqHB7JVccWDSw16uhJsbDZLRDhgCNbTSk4g/DKr1dnfLdQVGYNvk03kajMbBIrJuu7NsLHbjy/YABJlGOTo8RacCSiRWPC5pDiLnwMRXibM0owEn3qpqRb7HU8mhNUQJJlhB7IlGD/UHOuS/881p1Q6UbmoSn/N9rvE20LPFvcpbVFNc63L1xdJujS5/Oqy9QhFqcDjt9ZRpXLzN0jsQbctVimgUbdhOKTKbeFiHN/zNxz2Gt2SJZXfUyrHkf6hYPDm9r6CI8pJiXQLefijgEqcTOJjw8Uj3Tq007Ej/EiSGIkFBmVBkc1JbZbiXUgHYI2XVWZ8ZIn2+NBiKqqW/KdNysUh2r3iv5VMFxsLVjD4DAVXSpi6u2RaCq4xFJMM7o2pgffjOM4OsabnRhlHpBgmtu6jwc+X76yCkiHvkdtOMCvecTVMvT5Ga463C94P3GDzhh1Tp1aA="
    - secure: "xHRMiW59LM7hVCWzTGcWiR6VEEUe3ih/70AFdXQ6wPL26fSuxl4+4q4Xa0svwCKj8f2ZJPRnWxjXk/ctoBRynsfMUW99Vxqa8YDYPSzcct9ZseBr+p6k9edgxsqtqIrQI+atTxXc7IDrYmcZInnermxfPD8eYPfSgscsdMdpUtbLcDr8eVc28kZAg2TB5CqPSBWBwgTuAB0b25uxuowjv3s9WDjs1KVVTckhZgLdE/t0xR9hf3FlKng+nNrFv6OHsL8/7f69qLbrEvU+kRYuaInCZcd1o4UITbWzl0oe8mBdFlNvmO6NWOyk0XH4H/q6em9tzcMNx6Yt1Lm39fJhEIEqEYDuXSxms4B8uh23zEN/RAv7VXKJvo2eO2DXURAjkqPTdBW0EajsFk5wFfSI/o5Xtm2oDwwLG9SuW2gBfRnZgDEPF4ay61v4t+6z3TYH4fX9YH8OlkyF/t61gpOBMTARed799akYEkJ3ZdP9PL834ez+Q2ZtUQ5utlnEkTNfvXdIGu/IC3iSzCBmQBn+eSRaqr06X+gzGrJElAgD4nQGoT0+t+2tcBe0QoJcMrw25E8CjmD4RA/wiQMqAH3bfedUkVxZu6yr0AkU9z7/Ze8/SYGcNaTiXwI3ecWs93MFiE5DeWIUDToLR6acuoNL0QZbGiyElpbkShajXvNFHr8="
language: node_js

node_js:
    - lts/carbon    
    
install:    
    - npm install
   
script:    
    - npm run test  
 
before_deploy:    
    - if ! [ "$BEFORE_DEPLOY_RUN" ]; then  
        export BEFORE_DEPLOY_RUN=1; 
        git checkout master;
        npm version patch;        
        git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git;
        git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git --tags;
      fi

deploy:
  - provider: releases    
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
      repo: lectra-tech/ld-react-feature-flags
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE = *"MAKE_RELEASE"*  
  - provider: npm
    email: $NPM_EMAIL_TOKEN
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      repo: lectra-tech/ld-react-feature-flags
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE = *"MAKE_RELEASE"*      