language: node_js

node_js:
    - lts/carbon    
    
install:    
    - npm install
   
script:    
    - npm run test  
 
before_deploy:    
    - if ! [ "$BEFORE_DEPLOY_RUN" ]; then  
        export BEFORE_DEPLOY_RUN=1; 
        git checkout master;
        npm version patch;        
        git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git;
        git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git --tags;
      fi

deploy:
  - provider: releases    
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE = *"MAKE_RELEASE"*  
  - provider: npm
    email: $NPM_EMAIL_TOKEN
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE = *"MAKE_RELEASE"*      
