env:
  global:
    - secure: "cfnX1hTjao5VwIgf1BJVjfhET6o0SsUkwBMps+LIzWOy6Rkwy+W8VR86QcVZl+AJELEBZNhLIcEgEUIuR2edeiA4izhZH0bptkQzFndesI/RFpUQ/GVSZWNtugRPLBirZU/r0yJySnPhfU65ZC+Qk59YpVsFpr4Ycl+tIfGE9YbED08rr8dfK7K8RYovCcFxrQOS6Awwrwy0JonO4snB1S2wbzE9V/m9lkxdxub7/BAvoR7Z1exPcWiwQ8/N/sYwdSGKpkQBHGyhZQ/864CgCRddHshjJKvLawBrYWE++WrqvtyyAqctC+bN2mmpFUo5h4jRXuqh37LegVO65Yf26/aEe7uwkd5qJkk0W15U2noCeLoBGtKqDS7MQpT6zvbwqD9mY4KUmFn2K4pfi6bD8L5qXvSQI8yn+RyH3T0BfrXGdMH8mErvVe7MIoAswt8z5ijlCfjuVEM/IOzugOB1KxY46RtobV4efzDVe1lto4abOGieUxvfbsNtFotxEqPeUZPbz/KTJe9dQ9p5bdNY/hczZORQvD/e2Xr/8AvecXWkcNx/wZwIpkPnqmWlP2RIitTVScOqJvasxLQUWnwTyMCVg8mDzuaJ06e2cnVXksbRPaw0e2rG+kV7d89TCXlyFqlHZB8F8vdtoG7PTd8zMIG3YBUS7xH+yeRlWAx76yc="    
    - secure: "donSTJeWISfsV7MDor7vHje2Smo1ph6uChm6SJPPNhZk8U9rOH4Pdgp9oDdC4W9/eYuP1Ay/4wXogJCZwN1/HBeFfuPNBMdrlG28yikl+YwmuMYStqGkG5meTmsJoFDnFJdlwb4nW4jr5P/hLm+nmtynop++E2rkrzedV+f7wqtEuHgvrdaYj9HZLLdkOmkwOgYPTyyxvLwa5Ki0ik3Jud2TBPFkFormUKXOo7wswvUvZvH3+J2haBLC3Mg2zSlyM7u3O6Bdi68Jky56xGeJzYcf4bIAeOhHnuxRkPK81Qm/OnLiJodhq221s8OuQH5ILL5DebczdUsuQENvC+UZFZa52D53pKN7nbo4LYHY72chPvFbFpqkXn3pX6ZzC03XiuJjz1/zeY8UQf2m2fNcpWCEu0W14jamaX2eV/bu1eUwADYG323ycqe4Qz66tATwDnm/KgN4D95xU4eDKjPuf+IhU+5pnLaG2jiSs5a59jgK90qHLyKNtjtJVMtcQOsx3CrsegXg26pkixPOuNMQk9uYfh+v+Sv/SGA68gKWLrtsRWwyQODRlH00ALxPqcD4M0uKF5tnqLJ7EhO5NaV75WOaqqMTDvQZUyZEEAQ0/6i2I0wCM3kj1B3uyQR45jjy9ePEL/R+VkAi9wIvOMsJrvuZc57XAUhrwaFug/h08so="
    
language: node_js

node_js:
    - lts/carbon    
    
install:    
    - npm install
   
script:    
    - npm run test  
 
before_deploy:    
    - if ! [ "$BEFORE_DEPLOY_RUN" ]; then  
        export BEFORE_DEPLOY_RUN=1; 
        git checkout master;
        npm version patch;        
        git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git;
        git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git --tags;
      fi

deploy:
  - provider: releases    
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE = *"MAKE_RELEASE"*  
  - provider: npm
    email: $NPM_EMAIL_TOKEN
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE = *"MAKE_RELEASE"*      